---
title: "k-means"
author: "Alin Castillo (alincastillo1995@gmail.com)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Carga de bibliotecas
library(dplyr)
library(purrr)
library(skimr)

# Carga de funciones
source(file = "k-means-functions.R")
```

# Ejemplos de segmentación con K-Means

## Ejemplo: Data Iris

### Carga de datos

```{r}
data("iris")
dataIris <- 
  iris[,-5]
```

### Analisis de datos perdidos
```{r}
result <- 
  dataValidation(dataIris)

result
```

### Detección de valores atípicos
```{r}

x <- 
  dataIris$Sepal.Length

x <- 
  x[x < max(x)]


for(i in 1:length(x)){
  max <- max(x)
  x <- x[x < max]
  
}

datosOut <- 
  function(max, hampelFilter){
    if(max > hampelFilter){
      return(max)
    }
  }

max(dataIris$Sepal.Length) > hampelFilter(dataIris$Sepal.Length)$sup
```


### Analisis de la escala de los datos

```{r}
coefVariacion <- 
  function(x){
    sd <- 
      sd(x)
    med <- 
      abs(mean(x))
    return(round(sd/med*100, 2))
  }

map_dbl(.x = dataIris, .f = coefVariacion)
```

Escalamos los datos:
```{r}
 dataIris <- 
  scale(dataIris) %>% 
  as.data.frame()

map_dbl(.x = dataIris, .f = coefVariacion)
```



