---
title: "word_cloud - Notas Gestión"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidytext)
library(RColorBrewer)
library(wordcloud)
library(tidyr)
library(purrr)
require(sm)
```

```{r, warning=F, echo=F}
load(file = "../data/Notas_Depuradas_0119_0719.RData")

Notas <- Notas_Depuradas_0119_0719 %>% 
  unnest_tokens(word,Notas_depuradas)

otras_palabras <- c("s", "si", "x", "tres", "tal", "facts", "así", "sino",
                    "vez", "ser", "i", "ii", "ex", "d", "aid", "cite", "etc",
                    "dos", "ido", "ir", "allí", "dotó", "u", "alla", "cómo",
                    "aún", "irá", "alta", "través", "uu", "viene", "debe", "dijo",
                    "va", "par")

palabras <- c(stopwords::stopwords(language = "es"), 
              otras_palabras)

Notas_detention <- Notas %>% 
  filter(!(word %in% palabras))

wordcloud_custom <- function(grupo, df){
  print(grupo)
  set.seed(123)
  wordcloud(words = df$word, 
            freq = df$frecuencia,
            min.freq = 1, 
            max.words = Inf, 
            random.order = FALSE, 
            rot.per = 0.3, 
            scale = c(4, .5),
            colors = brewer.pal(8, "Dark2"))
}
  
df_Notas <- Notas_detention %>% 
  group_by(Id_Nota, word) %>% 
  count(word) %>%
  group_by(Id_Nota) %>% 
  mutate(frecuencia = n / n()) %>%
  arrange(Id_Nota, desc(frecuencia)) %>% 
  nest()

walk2(.x = df_Notas$Id_Nota, .y = df_Notas$data, .f = wordcloud_custom)
```

