---
title: "Partici贸n de matrices con 'Hmisc'"
author: "Alin Castillo (alincastillo1995@gmail.com)"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Informaci贸n Adicional
- [tidyr.tidyverse.org](https://tidyr.tidyverse.org/reference/nest.html)
- [yuzaR Data Science](https://www.youtube.com/watch?v=tQ8dC0oLTnA)

## Instalaci贸n del paquete
```{r, eval=FALSE}
install.packages("dplyr")
install.packages("tidyr")
```

## Carga de los paquetes
```{r, warning=FALSE, message=FALSE}
library(dplyr) # for %>% , group_by()
library(tidyr) # for nest()
```

# Creaci贸n del marco de datos
```{r}
df <- 
  data.frame(
    individuo = c("i1", "i1", "i2", "i2"),
    gen_a = c(1, 2, 2, 2),
    gen_b = c(3, 3, 1, 3),
    gen_c = c(4, 4, 1, 2))
```

# Agrupamiento por "individuo"
```{r}
df <- 
  df %>% 
  group_by(individuo) %>% 
  nest()

df$data
```

# Desagrupamiento de los datos
```{r}
df <- 
  df %>% 
  unnest(cols = c(data))

df
```

